// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCClU_mb0_N1_7yqjH_TULTIYpJ6M9ZNkA',
    appId: '1:546309141919:web:50b439c926603cf6b0f9aa',
    messagingSenderId: '546309141919',
    projectId: 'plantshop-481b3',
    authDomain: 'plantshop-481b3.firebaseapp.com',
    storageBucket: 'plantshop-481b3.firebasestorage.app',
    measurementId: 'G-LXRNJ6Q8VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV_wy-2lL62gT_GCRF45VGWCimdx97FnQ',
    appId: '1:546309141919:android:327681d2097a9e82b0f9aa',
    messagingSenderId: '546309141919',
    projectId: 'plantshop-481b3',
    storageBucket: 'plantshop-481b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyCKELxBeb_ROBVVpN-iemw6Z1TJBAQA',
    appId: '1:546309141919:ios:cf80eea40f0a1ca1b0f9aa',
    messagingSenderId: '546309141919',
    projectId: 'plantshop-481b3',
    storageBucket: 'plantshop-481b3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhyCKELxBeb_ROBVVpN-iemw6Z1TJBAQA',
    appId: '1:546309141919:ios:cf80eea40f0a1ca1b0f9aa',
    messagingSenderId: '546309141919',
    projectId: 'plantshop-481b3',
    storageBucket: 'plantshop-481b3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCClU_mb0_N1_7yqjH_TULTIYpJ6M9ZNkA',
    appId: '1:546309141919:web:c02eb59abf154daab0f9aa',
    messagingSenderId: '546309141919',
    projectId: 'plantshop-481b3',
    authDomain: 'plantshop-481b3.firebaseapp.com',
    storageBucket: 'plantshop-481b3.firebasestorage.app',
    measurementId: 'G-EZYB822CGN',
  );

}