// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVJibCVgqIKVIaK8J_gcXpuSYdp1y3YMo',
    appId: '1:91554586988:web:48d087753328689f605349',
    messagingSenderId: '91554586988',
    projectId: 'fir-shop-f7c59',
    authDomain: 'fir-shop-f7c59.firebaseapp.com',
    storageBucket: 'fir-shop-f7c59.appspot.com',
    measurementId: 'G-LQDQLE7NEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_w8G-bVH8v2XtFNB1aDa8LWY8TCwG7k',
    appId: '1:91554586988:android:b4253f7bdaac10c9605349',
    messagingSenderId: '91554586988',
    projectId: 'fir-shop-f7c59',
    storageBucket: 'fir-shop-f7c59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQguFh78Y7PTgj3bsiYy4Gy-2whsD8m48',
    appId: '1:91554586988:ios:08aa84e912034ce5605349',
    messagingSenderId: '91554586988',
    projectId: 'fir-shop-f7c59',
    storageBucket: 'fir-shop-f7c59.appspot.com',
    iosBundleId: 'com.example.firebaseShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQguFh78Y7PTgj3bsiYy4Gy-2whsD8m48',
    appId: '1:91554586988:ios:08aa84e912034ce5605349',
    messagingSenderId: '91554586988',
    projectId: 'fir-shop-f7c59',
    storageBucket: 'fir-shop-f7c59.appspot.com',
    iosBundleId: 'com.example.firebaseShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVJibCVgqIKVIaK8J_gcXpuSYdp1y3YMo',
    appId: '1:91554586988:web:a9779ff462c17b80605349',
    messagingSenderId: '91554586988',
    projectId: 'fir-shop-f7c59',
    authDomain: 'fir-shop-f7c59.firebaseapp.com',
    storageBucket: 'fir-shop-f7c59.appspot.com',
    measurementId: 'G-RC44DZSFS0',
  );

}